spring:
  datasource:
    url: jdbc:mysql://localhost/shopping?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  mail:
    host: smtp.qq.com
    username: 914405257@qq.com
    password: svlvabfwfsrobejc
    default-encoding: utf-8
    port: 465
    properties:
     mail:
      smtp:
       ssl:
        enable: true
      timeout: 2000
      socketFactory:
        port: 465
        class: javax.net.ssl.SSLSocketFactory
  devtools:
    add-properties: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss    #  全局时间格式化
    time-zone: GMT+8
#  servlet:
#    multipart:
#      location: /upload   47.106.160.226

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yang.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081
  servlet:
    context-path: /shop

pagehelper:
  reasonable: true


#集成支付宝沙箱
alipay:
  appId: 2021000119682537
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCATvE1lfeG73MbSSVc66NBWGPFs8OyKwiwwn44BHONH1t8qRwta6ONU7KlI+fRFuNdbt1JDraa9Oz4exOmj8Qm20+r+msnhijb9fMuIejxBdN6C932ivFN6b5y6WiN5lHDOHzitOvnxKDL+uUTzmGm6X4Hu3BtDjF3p1G2ynImTCYGHpbTVHhk2RWmn1N1Myd2O3jDU/0HbdHai692irMK7mij0Yn+K5NPBjDuR0CapDLbPmik0mqbmPtTsV/dxhBLuMNiwojORkXJb5kmBXL0KM2GfqXWZPeU+GBxjJOb8D+fNzvBFpsIzk/iJMUu6Lt8R+ZGtF0ZGaFadvWsSE11AgMBAAECggEAaW50zi94wiwoTZeBWCVYdO2Irn/Uoqax8W0gAi/GM4Q8zOa4/KmiLxNDjGdAqZNBKRlcRBgO/K2du2CG+SrRZ4x2nz6aplObZ4NmW9YJb2P2LidqMJhjSD51/D7HZzKGpP/ZvwAjiMMNzg9QBUJlA56BrSDcdQBgrY2Tm7wmqEha1ug1HPS106qZmqs2H1vEkv9Yzs9Mf61lCQv3XRi1pIYvbm03FVAkuVAD7KtH4k0SX+8BTRrYQzR/HBvkwrfaRvyn1AvP4H0ajphQ56LHo2HofALBXbzz6/ZJS9DPc4CWDhVenzXIX+j92l0vFD+TJehWKN9YAlNLYM8lENn8UQKBgQD03Ce7PUb99jdt+LAQqddTKcPK51HJ/f5W4ss09MPGAeTnYlvv+W3VndjOwvvihh/P2Whi88WmSXN3mFQoVjvj9F4jsfFuGSL/gFzxluqJlNrB6UzZyQfjMUMis207NC+RTirh6JTXzAsrwCZUbWhaPPvjXJ3Lnv92iyXEO+T3VwKBgQCGJVRCfX7aGGCFtmR3UiDrwAqg6z05t0zjdoomiAN+tDYwx+5SOX4gOKf8oBa7K6KKnF1xFpb2Q4U02r5mGp5TD7qxj8BVWUCU0bOZvDq6L4M7Lj7CQdCu9W3VZZ3C1Mjx8McTX4MToAO1PWsRFY31okXZpVxK2NaxkbcfwUheEwKBgQDf7vfnJYNnf2XyDR34H1vtkqSdTDBgqwmQLJnrNG5XCCRv+GRcc6EfW9yMO4ZhBIjTbeEpngeErGgNWCKfQT5Em5f8zSAfsJ1xTdOynnKgoKHv9Y1zH4c3IDZl5fJf0rouCW7ua+az9MfCm1hynhxxapRyuqEVN7QqlddUP/KGwQKBgCqs23ZfmChn0uUW1jVDcmeta3QwAgVHc/V085Q4duwrBoZURFPyKFa1z3NFtpWK1yXDgtKEPjhP2KOs5x9yXmXMPjdYpPZB85Kkd79zqzcqAFSmbJ6981aFi5B0yFCAAwE8+QgHvZpTsHpK9LG1qri3DAOmYIsLGpnY4mn+wjfzAoGAPmrsZB6cl4cNERHCw83JDXpOHR3EZT9Ags5JQkymTtXZuDe/86GrTqhenEGj5yTluT3G+BMUMa/o2aj7ZQdNwdupH5ws+DNBGSA9TemboKqe8VeFHIE/D6IbtygICsNzZwwRce6NuvrvwXj05MqQ/8GgtTDoapkXEsji2MB1KvY=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgE7xNZX3hu9zG0klXOujQVhjxbPDsisIsMJ+OARzjR9bfKkcLWujjVOypSPn0RbjXW7dSQ62mvTs+HsTpo/EJttPq/prJ4Yo2/XzLiHo8QXTegvd9orxTem+culojeZRwzh84rTr58Sgy/rlE85hpul+B7twbQ4xd6dRtspyJkwmBh6W01R4ZNkVpp9TdTMndjt4w1P9B23R2ouvdoqzCu5oo9GJ/iuTTwYw7kdAmqQy2z5opNJqm5j7U7Ff3cYQS7jDYsKIzkZFyW+ZJgVy9CjNhn6l1mT3lPhgcYyTm/A/nzc7wRabCM5P4iTFLui7fEfmRrRdGRmhWnb1rEhNdQIDAQAB
  #支付网关配置，这一项是写死的，正式环境是openapi.alipay.com
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  #支付成功之后的回调页面，只是一个友好页面。主要换成你自己映射的临时域名
  returnUrl: http://47.106.160.226:8081/shop/order/success
  #支付成功的接口回调，我们还没写，先空着
  notifyUrl: http://47.106.160.226:8081/shop/order/success
  signType: RSA2
  charset: utf-8
